### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by steckerhalter** [emanuelfeld/poirot#1]
```
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/user/bin/poirot", line 11, in <module>
    sys.exit(main())
  File "/home/user/.pyenv/versions/user/local/lib/python2.7/site-packages/poirot/poirot.py", line 21, in main
    investigator.search(utf8_decode(pattern))
  File "/home/user/.pyenv/versions/user/local/lib/python2.7/site-packages/poirot/poirot.py", line 46, in search
    self.add_committed_results(pattern)
  File "/home/user/.pyenv/versions/user/local/lib/python2.7/site-packages/poirot/poirot.py", line 87, in add_committed_results
    merge_committed("diff", commit_range)
  File "/home/user/.pyenv/versions/user/local/lib/python2.7/site-packages/poirot/poirot.py", line 83, in merge_committed
    for commit, metadata in self.search_committed(target, pattern, commit_range):
  File "/home/user/.pyenv/versions/user/local/lib/python2.7/site-packages/poirot/poirot.py", line 108, in search_committed
    file_diffs = self.parse_diff(diff=out, pattern=pattern)
  File "/home/user/.pyenv/versions/user/local/lib/python2.7/site-packages/poirot/poirot.py", line 220, in parse_diff
    matches = [m for m in find_matches_in_diff(diff_text)]
  File "/home/user/.pyenv/versions/user/local/lib/python2.7/site-packages/poirot/poirot.py", line 198, in find_matches_in_diff
    line = utf8_decode(line)
  File "/home/user/.pyenv/versions/user/local/lib/python2.7/site-packages/poirot/utils.py", line 75, in utf8_decode
    return text.decode("utf-8")
  File "/home/user/.pyenv/versions/user/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 28: invalid continuation byte
```

This seems to be related to a repo that contains ISO-8859-1 encoded text. I added this to `utils.py`: 

```python
def utf8_decode(text):
    try:
        return text.decode("utf-8")
    except AttributeError:
        return text
    except UnicodeDecodeError: # workaround for decoding error
        return text.decode("ISO-8859-1")
```

This fixes the problem but there may be a better solution...

**Comment by emanuelfeld** [comment]
Sorry for delay. The libraries for guessing the encoding scheme are rubbish in my experience. I'm thinking I'll add flags for the encoding used in the patterns/regexps and in the directory's files (ordered by precedence), e.g.:

`poirot --revlist="all" --pattern-encoding="utf8" --file-encodings="utf8,latin1,ISO-8869-1,big5"`

and swap utf8_decode with:

```
def decode(text, encodings=['utf8', 'latin1']):
    try:
        return text.decode(encodings[0])
    except UnicodeDecodeError:
        return decode(text, encodings[1:])
    except IndexError:
        print(style("Invalid encoding for: {}\n".format(text), "red"))
        raise UnicodeDecodeError
```

**Comment by steckerhalter** [comment]
No problem. How about `chardet` mentioned here: http://stackoverflow.com/questions/269060/is-there-a-python-library-function-which-attempts-to-guess-the-character-encodin

It could still fall back on the file encodings list...

**Comment by emanuelfeld** [comment]
Tried out chardet and it has unfortunately performed poorly. I think Nick at your link has it right. Just have to decide how I want to handle errors.
